name: decapitalgrille
description: Hospitality Redefined

publish_to: "none"

version: 2025.06.25+8

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0
  # flutter_screenutil: ^5.5.3+2
  http: ^1.2.2
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  device_info_plus: ^11.1.0
  restart_app: ^1.3.2
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  quick_actions: ^1.0.8
  palette_generator: ^0.3.3+4
  # Custom Snackbar
  fluttersnackbar:
    path: packages/fluttericonsnackbar
  caroulina:
    path: packages/caroulina
  # WooCommerce
  woocommerce:
    path: packages/woocommerce
  # Payment with Paystack
  paystack:
    path: packages/paystack
  # Daniel Abugre's themed spins
  niel_spins:
    path: packages/niel_spins
  video_shop_flutter:
    path: packages/video_shop_flutter
  #  pinput: ^2.2.11
  url_launcher: ^6.3.1
  in_app_review: ^2.0.9
  share_plus: ^10.0.3
  html_unescape: ^2.0.0 # Might Remove it
  qr_code_scanner: ^1.0.1
  story_view: ^0.16.5
  map_launcher: ^3.5.0
  flutter_svg: ^2.0.10+1
  pull_to_refresh: ^2.0.0
  upgrader: ^11.3.0
  webview_flutter: ^4.10.0 # Might Remove it
  emailjs: ^4.0.0
  posthog_flutter: ^4.0.0
  flutter_local_notifications: ^17.2.3
  local_auth: ^2.3.0
  permission_handler: ^11.3.1
  timezone: ^0.9.4
  animated_text_kit: ^4.2.2
  flutter_easyloading: ^3.0.5
  ndialog: ^4.3.1
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^6.0.5
  network_info_plus: ^6.1.0
  flutter_native_splash: ^2.4.1
  fluentui_system_icons: ^1.1.260

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_native_splash:
  color: "#ffffff"
  image: "images/degrille/icon/logo.png"
  background_image: "images/app/splashscreen.png"
  icon_background_color: "#ffffff"
  android_12:
    image: "images/degrille/icon/logo.png"
    background_image: "images/app/splashscreen.png"
    color: "#ffffff"
    icon_background_color: "#ffffff"
  web: false

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "images/icon/icon.png"

flutter:
  assets:
    - images/
    - images/app/
    - images/blog/
    - images/errors/
    - images/account/
    - images/degrille/
    - images/degrille/icon/
    - images/cart/
    - images/contact/
    - images/categories/
    - images/other/
    - images/order/
    - images/icons/
    - i18n/en.json
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans/DMSans-VariableFont_opsz,wght.ttf
        - asset: fonts/DMSans/DMSans-Italic-VariableFont_opsz,wght.ttf
          style: italic
