name: caroulina
description: Another Flutter carousel package for perfectionists with deadlines.
version: 2.0.6
homepage: https://github.com/naabatechs/caroulina
license: MIT
issue_tracker: https://github.com/naabatechs/caroulina/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
