name: niel_spins
publish_to: none
description: A collection of loading indicators and animations. Inspired by @tobiasahlin's SpinKit.
version: 5.2.1
homepage: https://github.com/jabaapplets/niel_spins

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
